FROM node:latest

# Install dependencies
RUN apt-get update && \
    apt-get install -y git && \
    npm install -g n && \
    n stable && \
    npm install -g pm2

# Clone and install the application
# RUN git clone https://github.com/CryptoGnome/Bybit-Lick-Hunter-v4.git /app

COPY ./bybit /app

WORKDIR /app

RUN npm install

# Start the application with pm2
CMD ["pm2-runtime", "app.js"]